### PR TITLE
Update Angular

### PR DESCRIPTION
**Pull request by rexx0520**
Update Angular to latest version to bypass Firefox ext security test when this ext is converted to xpi using Chrome Store Foxified.

### CODE REVIEW

**Comment by Kyle-Kyle** [comment]
...Your version is 1.5.8..And my version 1.6.4...I guess yours is older?

**Comment by rexx0520** [comment]
...but this version bypassed the security checkment..

**Comment by Kyle-Kyle** [comment]
I think the latest should be adopted.
You can use yours to create xpi.

**Comment by rexx0520** [comment]
how about 1.6.5

**Pull request merged**
